"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cmd_wheel_mode_t(object):
    __slots__ = ["cmd_wheel_linear_vel", "cmd_wheel_angular_vel", "cmd_wheel_heading_hold", "cmd_target_heading"]

    def __init__(self):
        self.cmd_wheel_linear_vel = 0.0
        self.cmd_wheel_angular_vel = 0.0
        self.cmd_wheel_heading_hold = 0
        self.cmd_target_heading = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(cmd_wheel_mode_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffif", self.cmd_wheel_linear_vel, self.cmd_wheel_angular_vel, self.cmd_wheel_heading_hold, self.cmd_target_heading))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cmd_wheel_mode_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cmd_wheel_mode_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cmd_wheel_mode_t()
        self.cmd_wheel_linear_vel, self.cmd_wheel_angular_vel, self.cmd_wheel_heading_hold, self.cmd_target_heading = struct.unpack(">ffif", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cmd_wheel_mode_t in parents: return 0
        tmphash = (0xf4e5c8c8843cef36) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cmd_wheel_mode_t._packed_fingerprint is None:
            cmd_wheel_mode_t._packed_fingerprint = struct.pack(">Q", cmd_wheel_mode_t._get_hash_recursive([]))
        return cmd_wheel_mode_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

