"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cmd_brush_t(object):
    __slots__ = ["cmd_brush_power", "cmd_brush_enable", "cmd_water_flow", "cmd_water_enable"]

    def __init__(self):
        self.cmd_brush_power = 0
        self.cmd_brush_enable = 0
        self.cmd_water_flow = 0
        self.cmd_water_enable = 0

    def encode(self):
        buf = BytesIO()
        buf.write(cmd_brush_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">iiii", self.cmd_brush_power, self.cmd_brush_enable, self.cmd_water_flow, self.cmd_water_enable))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cmd_brush_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cmd_brush_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cmd_brush_t()
        self.cmd_brush_power, self.cmd_brush_enable, self.cmd_water_flow, self.cmd_water_enable = struct.unpack(">iiii", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cmd_brush_t in parents: return 0
        tmphash = (0xc05f57014f08894f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cmd_brush_t._packed_fingerprint is None:
            cmd_brush_t._packed_fingerprint = struct.pack(">Q", cmd_brush_t._get_hash_recursive([]))
        return cmd_brush_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

