"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class state_floating_mode_t(object):
    __slots__ = ["sta_floating_vel_x", "sta_floating_vel_y", "sta_floating_vel_z", "sta_floating_angular_x", "sta_floating_angular_y", "sta_floating_angular_z", "sta_thruster_power", "sta_thruster_temp"]

    def __init__(self):
        self.sta_floating_vel_x = 0.0
        self.sta_floating_vel_y = 0.0
        self.sta_floating_vel_z = 0.0
        self.sta_floating_angular_x = 0.0
        self.sta_floating_angular_y = 0.0
        self.sta_floating_angular_z = 0.0
        self.sta_thruster_power = [ 0.0 for dim0 in range(4) ]
        self.sta_thruster_temp = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(state_floating_mode_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffffff", self.sta_floating_vel_x, self.sta_floating_vel_y, self.sta_floating_vel_z, self.sta_floating_angular_x, self.sta_floating_angular_y, self.sta_floating_angular_z))
        buf.write(struct.pack('>4f', *self.sta_thruster_power[:4]))
        buf.write(struct.pack('>4f', *self.sta_thruster_temp[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != state_floating_mode_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return state_floating_mode_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = state_floating_mode_t()
        self.sta_floating_vel_x, self.sta_floating_vel_y, self.sta_floating_vel_z, self.sta_floating_angular_x, self.sta_floating_angular_y, self.sta_floating_angular_z = struct.unpack(">ffffff", buf.read(24))
        self.sta_thruster_power = struct.unpack('>4f', buf.read(16))
        self.sta_thruster_temp = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if state_floating_mode_t in parents: return 0
        tmphash = (0x8d54987e089af3b8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if state_floating_mode_t._packed_fingerprint is None:
            state_floating_mode_t._packed_fingerprint = struct.pack(">Q", state_floating_mode_t._get_hash_recursive([]))
        return state_floating_mode_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

