"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class state_robot_t(object):
    __slots__ = ["sta_position_x", "sta_position_y", "sta_position_z", "sta_roll", "sta_pitch", "sta_yaw"]

    def __init__(self):
        self.sta_position_x = 0.0
        self.sta_position_y = 0.0
        self.sta_position_z = 0.0
        self.sta_roll = 0.0
        self.sta_pitch = 0.0
        self.sta_yaw = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(state_robot_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffffff", self.sta_position_x, self.sta_position_y, self.sta_position_z, self.sta_roll, self.sta_pitch, self.sta_yaw))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != state_robot_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return state_robot_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = state_robot_t()
        self.sta_position_x, self.sta_position_y, self.sta_position_z, self.sta_roll, self.sta_pitch, self.sta_yaw = struct.unpack(">ffffff", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if state_robot_t in parents: return 0
        tmphash = (0xa9d91f62ddeca0e7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if state_robot_t._packed_fingerprint is None:
            state_robot_t._packed_fingerprint = struct.pack(">Q", state_robot_t._get_hash_recursive([]))
        return state_robot_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

